name: Run MATLAB Build on GitHub-Hosted Runner 
on: 
  workflow_dispatch
jobs:
  my-job:
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB_Compiler         
          release: R2024a
      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          tasks: check test   
      - name: Upload artifact
        uses: actions/upload-artifact@v4  
        with:          
          name: app
          path: ./*standalone*/*timestable*
          
      # - name: Run tests and generate artifacts
      #   uses: matlab-actions/run-tests@v1
      #   with:
      #     test-results-junit: test-results/results.xml
      #     code-coverage-cobertura: code-coverage/coverage.xml
      #     source-folder: source
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: cc
      #     path: code-coverage/coverage.xml 
      # - uses: actions/upload-artifact@v2
      #   with:          
      #     name: tr
      #     path: test-results/results.xml
